version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/marketplace
      - JWT_SECRET=u7#2Jz!m4Q1pT6aR9wE3dS0xY8kC5vF2
      - SESSION_SECRET=w9$2hT!b7X9z@1Pf4H2kR8sM5e3qV6cL
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network
    command: >
      bash -c "
        sleep 10 &&
        npm run build &&
        npm run seed &&
        npm start
      "

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
